### ISSUE TITLE
Errors after moving from old repo to luuuis repo

### ISSUE THREAD

**Issue by carlosCastro99** [luuuis/hass_wibeee#11]
Luis,

hi. Yesterday I moved from abacao to your version, however I'm facing new (different) errors

![image](https://user-images.githubusercontent.com/29844157/132578876-e25db9be-ba16-4283-a809-ad5cb3618942.png)

Error getting http://192.168.31.228:80/en/status.xml, will retry. ExpatError: mismatched tag: line 48, column 25
21:11:04 – (AVISO) wibeee (custom integration) - mensagem ocorreu primeiro em 21:09:34 e repetiu-se 2 vezes
Error getting http://192.168.31.228:80/en/status.xml, will retry. ServerDisconnectedError: Server disconnected
21:08:49 – (AVISO) wibeee (custom integration)
Error getting http://192.168.31.228:80/en/status.xml, will retry. TimeoutError:
21:08:41 – (AVISO) wibeee (custom integration)

**Comment by carlosCastro99** [comment]
also, after moving to your version my device got disconnected. I noticed that before when I tried the API integration. It seems that if the device detects to many attemps it disconnects from wifi. After I stopped HA is reconnected successfully.
with abacao version I used 5s periodicity.

**Comment by carlosCastro99** [comment]
Luis,

tive mesmo que voltar à versão anterior, apesar de ter aproveitado algumas das tuas mudanças.

![image](https://user-images.githubusercontent.com/29844157/132857499-c40172cc-b235-4b3c-aeab-7b216e00bf22.png)

repara na diferença de estabilidade de informação de um para outro. às 10AM mudei novamente para abacao, e o grafico é muito mais estavel, sem interrupções e especialmente sem causar o offline do wibeee

**Comment by luuuis** [comment]
Hi @carlosCastro99 ,

Apologies for the delay, I did not have notifications enabled for this repository.

1. The reason that there are different errors in the logs is because I've added more detailed error logging in https://github.com/luuuis/hass_wibeee/pull/8. This does not mean that they are new errors, simply the log now contains more information now (useful for reporting bugs).

2. Regarding the sensors becoming unavailable, this is also not what it seems. What happens is that the juanjoSanz and abacao versions do not set the sensors to unavailable ever, even when there is an error encountered. When there is an error they simply do not update the sensor (you see this by looking at the `Last changed` time in https://my.home-assistant.io/redirect/developer_states/). So the previous versions (and other forks) _appear_ to not become unavailable but really they are only hiding real problems with the Wibeee hardware / firmware. Does that make sense? In my version I have changed this because I want to be able to know when the Wibeee monitor is down and I do not want stale and wrong values to be reported if the Wibeee is down.


> abacao version I used 5s periodicity.

Are you sure? acabao's version does not support `scan_interval`, it is [hard-coded to 15s](https://github.com/abacao/hass_wibeee/blob/master/sensor.py#L73) and can not be changed. Did you modify the source code? I have found 5s to not be stable on my monitor as well so I suggest to keep the default of 15s (or maybe try 10s or lower until you find it is stable).

I have planned some changes to the component that I think will allow for more frequent updates but I haven't had time to implement those yet.

Hope this helps.
