### ISSUE TITLE
Error `Attribute hass is None for <Entity ...>` when any of the sensors is disabled

### ISSUE THREAD

**Issue by t3lmoazevedo** [luuuis/hass_wibeee#14]
Installed yesterday, and for now it only updates de L1 values.
Using it for 2 devices.
What should be the problem?
Thanks!

sensor:
- platform: wibeee
  host: 192.168.7.62 # piso -1
  scan_interval: 5
- platform: wibeee
  host: 192.168.7.63 # piso 0
  scan_interval: 5

![Captura de ecrã 2021-12-02 153744](https://user-images.githubusercontent.com/41584793/144453590-677861ab-e93c-43a1-902b-2aa36044ad62.png)
.

**Comment by luuuis** [comment]
I'm not sure how that can happen since L1/L2/L3 all come in the same response. What I can say is that `scan_interval: 5` might be too aggressive and could cause problems on the device (normally this causes errors while fetching status.xml).

Could you turn on debug logging and share the relevant portions?
https://github.com/luuuis/hass_wibeee#logging

**Comment by t3lmoazevedo** [comment]
Removed scan_interval and added log.
Same result with frozen L2 and L3, and the source XML are ok.
Any more similar reports?

![Captura de ecrã 2021-12-02 213331](https://user-images.githubusercontent.com/41584793/144506663-780f156f-b357-431e-8dfe-214b43492ad1.png)

sensor:
- platform: wibeee
  host: 192.168.7.62 # piso -1
- platform: wibeee
  host: 192.168.7.63 # piso 0

logger:
  default: warn
  logs:
    custom_components.wibeee.sensor: info

2021-12-02 21:17:46 INFO (MainThread) [custom_components.wibeee.sensor] Initializing WibeeeData with host: 192.168.7.62, scan_interval: 0:00:15, timeout 0:00:10, max_wait: 0:00:05
2021-12-02 21:17:46 INFO (MainThread) [custom_components.wibeee.sensor] Initializing WibeeeData with host: 192.168.7.63, scan_interval: 0:00:15, timeout 0:00:10, max_wait: 0:00:05

**Comment by luuuis** [comment]
Please include all logs from the custom component after startup and until L2/L3 freeze. Unfortunately, I don't have two devices to test with simultaneously.

Also as a troubleshooting step could you enable only one of the sensors and check if the same happens?

**Comment by t3lmoazevedo** [comment]
Working with 1 sensor now and freezes also L2/L3.
Here are the logs fo far...
![Captura de ecrã 2021-12-02 215648](https://user-images.githubusercontent.com/41584793/144509726-9022ea25-ef86-4f02-b694-66014134dc9f.png)

**Comment by t3lmoazevedo** [comment]
Commented the Reactive sensors from SENSOR_TYPES and now only freezes L3
Logs...

![Captura de ecrã 2021-12-02 221929](https://user-images.githubusercontent.com/41584793/144512405-0f068cd8-cb79-473e-a2fb-b8cf7961e625.png)

**Comment by luuuis** [comment]
@t3lmoazevedo do you have any entities from the Wibeee integration that are disabled?

**Comment by t3lmoazevedo** [comment]
@luuuis yes I do, the ones I don't need to archive values. It's possible to skip them or should I need to add them all?

**Comment by luuuis** [comment]
Probably the custom component doesn't handle disabled entities as it should. It looks straightforward to implement and I can look into it later but for now you can exclude the entities in the Recorder and keep them enabled.
https://www.home-assistant.io/integrations/recorder/#exclude

Let me know if that fixes the issue.

**Comment by t3lmoazevedo** [comment]
Working now after all enabled. Thank you for the debug also.

**Comment by luuuis** [comment]
The fix for this is now available in https://github.com/luuuis/hass_wibeee/releases/tag/v3.0.0-beta.2.

**Comment by luuuis** [comment]
Starting in [v3.1.0](https://github.com/luuuis/hass_wibeee/releases/tag/v3.1.0) each sensors is assigned to one of 4 Devices:
- a main Device for the totals (L4)
- one extra Device for each of L1/L2/L3 clamps.

This means that if you are only using one clamp you can disable the devices for the other two clamps and every sensor under that will be disabled.

If you are concerned with avoiding long term storage rather than simply wanting the sensors to be go away completely then the `recorder` approach still seems more appropriate.
