### ISSUE TITLE
Logo não aparece

### ISSUE THREAD

**Issue by joaopedros2** [luuuis/hass_wibeee#54]
Sei que poderá não ser muito importante mas ficava esteticamente mais agradável se a integração tivesse um logo.
No meu caso não tem.
![Screenshot_2023-01-21-23-59-49-43_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/50808090/213894729-f0a7ba84-adbb-490c-9bb9-76b2b553b141.jpg)

**Comment by luuuis** [comment]
Thanks for the report @joaopedros2. I believe this was working previously, maybe something changed in how HA branding is serving up the logo.

In any case I created https://github.com/home-assistant/brands/pull/4059 to add the Wibeee icons for use in those views.

**Comment by luuuis** [comment]
The icon has been added but will take time to consistently show up due to [CDN caching](https://github.com/home-assistant/brands#caching) (7 days, could be less if there is a new HA release).

![Settings – Home Assistant 2023-01-23 16-30-58](https://user-images.githubusercontent.com/161006/214094845-629a517c-f8ec-420d-b70e-fea1dc7e5d2b.jpg)

**Comment by joaopedros2** [comment]
Thanks. Now it's looking good 👍
