### ISSUE TITLE
Add option to change the IP address of a device that is already configured

### ISSUE THREAD

**Issue by edurenye** [luuuis/hass_wibeee#59]
Right now through the UI, the only option is to remove the device and add it again, so would be nice to be able to change the IP the same way we can change the name or the zone.

**Comment by luuuis** [comment]
That sounds reasonable, @edurenye. Can I ask what was the reason for changing the device IP?

Do you use the optional [Local Push support](https://github.com/luuuis/hass_wibeee#configuring-local-push-optional-advanced)?

**Comment by edurenye** [comment]
Thanks for your fast answer and for your work in this component.
I got a new router with new network that does not allow me to change it (a weird one 192.168.8.x) and set new IP's to all the devices. 
Also just feels natural to be able to change the IP's.
And no, I don't use the 'Local Push support'.

**Comment by luuuis** [comment]
Ok so it turns out that (1) this is very easy to implement and (2) the user experience for it is really weird. What you have to do is:
1. Leave the old integration, the one with the wrong IP address, untouched.
3. **Add** a new integration of the same type and use the _new_ IP address in the prompt as if you were adding a new device.
  ![Settings – Home Assistant 2023-03-09 00-16-14](https://user-images.githubusercontent.com/161006/223882589-fb394823-8188-4239-bfb5-22926794226d.jpg)
4. Click _Submit_. You should see the following pop up.
  ![Settings – Home Assistant 2023-03-09 00-15-27](https://user-images.githubusercontent.com/161006/223882156-e1521f6d-d707-406a-a633-ed75eaa4917b.jpg)

It turns out that HA will update the integration with the new data (including IP address) before it displays this message. This is how it's designed to work and I have no control over the weird UX.

You need [v3.2.4](https://github.com/luuuis/hass_wibeee/releases/tag/v3.2.4) for this to work, otherwise the IP address is not updated.

**Comment by edurenye** [comment]
Ok, thank you very much!
