### ISSUE TITLE
Solar panels configuration

### ISSUE THREAD

**Issue by soth78** [luuuis/hass_wibeee#63]
Hi!

I've got solar panels, and I can't figure out the configuration needed to use the solar panel figure of the energy panel on hass,

could I get some assistance on this?

**Comment by luuuis** [comment]
@soth78 have you checked the examples in https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples ?

**Comment by soth78** [comment]
HI @luuuis , thanks for the fast reply?

Yes, I checked that and I've configured based on that. The result is the graph of energy pulled and returned, but not showing how much the solar panels are actually producing at any given time, that's why I was wondering if that example can be adapted to have solar panel output, consumed by the house, returned to the network, and house consuming network energy instead

**Comment by luuuis** [comment]
To get the energy being produced at the solar panels you need to:
1. get the value from your solar inverter (using its own Home Assistant integration), or
2. add another CT clamp to the Wibeee to measure the solar production only and set up another energy sensor (e.g. `solar_export_power` and `solar_export_energy`).

That will give you this value in HA:

![Home Assistant - Home – Home Assistant 2023-05-22 10-47-45](https://github.com/luuuis/hass_wibeee/assets/161006/afdfb5e6-8ac6-441d-85fa-ea1adbbf9948)

The `solar_export_power` and `solar_export_energy` sensors are configured exactly as in https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples but instead of (for example) `sensor.wibeee_phase1_active_power` you might use `sensor.wibeee_phase3_active_power` for the other clamp. Make sense?

![Settings – Home Assistant 2023-05-22 10-40-21](https://github.com/luuuis/hass_wibeee/assets/161006/b632976d-96e2-41b5-95c2-9c7224466307)

For the `solar_` sensors you can use another Wibeee, an extra clamp on the same Wibeee or another energy monitoring device. Hope this helps.

**Comment by soth78** [comment]
Hi!

What I'm seein on the wibeee is that L2 contains the solar panels data, could this be the case? (comparing L2 with the Iberdrola app showing the output of the solar panels)

**Comment by luuuis** [comment]
Yes, any of the clamps could measure the solar production.
